### ISSUE TITLE
Missing file from Readme.md

### ISSUE THREAD

**Issue by JermellB** [alea-institute/folio-python#7]
If you click on the link to contribution guidelines on github you get the message: The main branch of soli-python does not contain the path CONTRIBUTING.md.

![image](https://github.com/user-attachments/assets/484a69b3-226e-4d09-a431-34e382ea0ee4)

**Comment by mjbommar** [comment]
Great to see your name again after all these years :smile: 

This should be fixed up now:
https://github.com/alea-institute/soli-python/blob/main/CONTRIBUTING.md
